### ISSUE TITLE
exception migrating pretix after installing the plugin

### ISSUE THREAD

**Issue by bcastillov-esp** [pretix/pretix-covid-certificates#2]
I tried to install the plugin, following this instructions on pretix marketplace:
[https://marketplace.pretix.eu/products/covid-certificates/](url)

```
$ source /var/pretix/venv/bin/activate
(venv)$ pip install pretix-covid-certificates
(venv)$ python -m pretix migrate
(venv)$ python -m pretix rebuild
# systemctl restart pretix-web pretix-worker
```

When I run the line: python -m pretix migrate
Pretix show this exception:

(venv) idmjiuser@webidmjisrv:~$ python -m pretix migrate
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/var/pretix/venv/lib/python3.6/site-packages/pretix/__main__.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/var/pretix/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 86, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/var/pretix/venv/lib/python3.6/site-packages/django/db/migrations/loader.py", line 274, in build_graph
    raise exc
  File "/var/pretix/venv/lib/python3.6/site-packages/django/db/migrations/loader.py", line 248, in build_graph
    self.graph.validate_consistency()
  File "/var/pretix/venv/lib/python3.6/site-packages/django/db/migrations/graph.py", line 195, in validate_consistency
    [n.raise_error() for n in self.node_map.values() if isinstance(n, DummyNode)]
  File "/var/pretix/venv/lib/python3.6/site-packages/django/db/migrations/graph.py", line 195, in <listcomp>
    [n.raise_error() for n in self.node_map.values() if isinstance(n, DummyNode)]
  File "/var/pretix/venv/lib/python3.6/site-packages/django/db/migrations/graph.py", line 58, in raise_error
    **raise NodeNotFoundError(self.error_message, self.key, origin=self.origin)
django.db.migrations.exceptions.NodeNotFoundError: Migration pretix_covid_certificates.0001_initial dependencies reference nonexistent parent node ('pretixbase', '0193_auto_20210611_1355')**

**Comment by raphaelm** [comment]
What version of pretix do you use?
